spark_version: 3.2.0
spark_hadoop_version: 3.2
spark_scala_version: 2.13
spark_download_url: "https://dlcdn.apache.org/spark/spark-{{ spark_version }}/spark-{{ spark_version }}-bin-hadoop{{ spark_hadoop_version }}-scala{{ spark_scala_version }}.tgz"

spark_force_install: false

spark_install_dir: /opt/spark
spark_home: "{{ spark_install_dir }}/spark-{{ spark_version }}-bin-hadoop{{ spark_hadoop_version }}-scala{{ spark_scala_version }}"
spark_config_dir: "{{ spark_home }}/conf"
spark_eventlog_dir: "file:/tmp/spark-events"
spark_history_port: 18080

spark_user_name: spark
spark_user_group: spark

spark_defaults:
  spark.master: "spark://localhost:7077"
  spark.driver.memory: "6g"
  spark.executor.memory: "6g"
  spark.eventLog.enabled: "true"
  spark.eventLog.dir: "{{ spark_eventlog_dir }}"
  spark.history.provider: "org.apache.spark.deploy.history.FsHistoryProvider"
  spark.history.fs.logDirectory: "{{ spark_eventlog_dir }}"
  spark.history.fs.update.interval: "10s"
  spark.history.ui.port: "{{ spark_history_port }}"
