---
- include_tasks: stop_cluster.yml
  when: spark_stop_cluster|default('false')|bool

- include_tasks: setup_cluster.yml
  when: spark_setup_cluster|default('false')|bool

- include_tasks: start_cluster.yml
  when: spark_start_cluster|default('false')|bool

