---
- name: Update apt repo and cache
  become: yes
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Upgrade apt packages
  become: yes
  apt:
    upgrade: dist
    force_apt_get: yes

- name: Install required packages
  become: yes
  apt:
    pkg:
      - unzip

- name: Check if reboot is needed
  become: yes
  register: reboot_required
  stat:
    path: /var/run/reboot-required
    get_md5: no

- name: Reboot the server
  become: yes
  reboot:
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 30
    test_command: uptime
  when: reboot_required.stat.exists
